<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Champion; 

class LaneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $championLanes = [
            'Aatrox' => 'Top',
            'Ahri' => 'Middle',
            'Akali' => 'Middle', 
            'Akshan' => 'Middle',
            'Alistar' => 'Support',
            'Amumu' => 'Jungle',
            'Anivia' => 'Middle',
            'Annie' => 'Middle',
            'Aphelios' => 'Bottom',
            'Ashe' => 'Bottom',
            'AurelionSol' => 'Middle',
            'Azir' => 'Middle',
            'Bard' => 'Support',
            'Belveth' => 'Jungle',
            'Blitzcrank' => 'Support',
            'Brand' => 'Support',
            'Braum' => 'Support',
            'Briar' => 'Jungle',
            'Caitlyn' => 'Bottom',
            'Camille' => 'Top',
            'Cassiopeia' => 'Middle',
            'Chogath' => 'Top',
            'Corki' => 'Middle',
            'Darius' => 'Top',
            'Diana' => 'Jungle',
            'Draven' => 'Bottom',
            'DrMundo' => 'Top',
            'Ekko' => 'Middle',
            'Elise' => 'Jungle',
            'Evelynn' => 'Jungle',
            'Ezreal' => 'Bottom',
            'Fiddlesticks' => 'Jungle',
            'Fiora' => 'Top',
            'Fizz' => 'Middle',
            'Galio' => 'Middle',
            'Gangplank' => 'Top',
            'Garen' => 'Top',
            'Gnar' => 'Top',
            'Gragas' => 'Jungle',
            'Graves' => 'Jungle',
            'Gwen' => 'Top',
            'Hecarim' => 'Jungle',
            'Heimerdinger' => 'Middle',
            'Hwei' => 'Middle',
            'Illaoi' => 'Top',
            'Irelia' => 'Top',
            'Ivern' => 'Jungle',
            'Janna' => 'Support',
            'JarvanIV' => 'Jungle',
            'Jax' => 'Top',
            'Jayce' => 'Top',
            'Jhin' => 'Bottom',
            'Jinx' => 'Bottom',
            'Kaisa' => 'Bottom',
            'Kalista' => 'Bottom',
            'Karma' => 'Support',
            'Karthus' => 'Jungle',
            'Kassadin' => 'Middle',
            'Katarina' => 'Middle',
            'Kayle' => 'Top',
            'Kayn' => 'Jungle',
            'Kennen' => 'Top',
            'Khazix' => 'Jungle',
            'Kindred' => 'Jungle',
            'Kled' => 'Top',
            'KogMaw' => 'Bottom',
            'KSante' => 'Top',
            'Leblanc' => 'Middle',
            'LeeSin' => 'Jungle',
            'Leona' => 'Support',
            'Lillia' => 'Jungle',
            'Lissandra' => 'Middle',
            'Lucian' => 'Bottom',
            'Lulu' => 'Support',
            'Lux' => 'Middle',
            'Malphite' => 'Top',
            'Malzahar' => 'Middle',
            'Maokai' => 'Jungle',
            'MasterYi' => 'Jungle',
            'Milio' => 'Support',
            'MissFortune' => 'Bottom',
            'Mordekaiser' => 'Top',
            'Morgana' => 'Support',
            'Naafiri' => 'Middle',
            'Nami' => 'Support',
            'Nasus' => 'Top',
            'Nautilus' => 'Support',
            'Neeko' => 'Middle',
            'Nidalee' => 'Jungle',
            'Nilah' => 'Bottom',
            'Nocturne' => 'Jungle',
            'Nunu' => 'Jungle',
            'Olaf' => 'Top',
            'Orianna' => 'Middle',
            'Ornn' => 'Top',
            'Pantheon' => 'Support',
            'Poppy' => 'Top',
            'Pyke' => 'Support',
            'Qiyana' => 'Middle',
            'Quinn' => 'Top',
            'Rakan' => 'Support',
            'Rammus' => 'Jungle',
            'RekSai' => 'Jungle',
            'Rell' => 'Support',
            'RenataGlasc' => 'Support',
            'Renekton' => 'Top',
            'Rengar' => 'Jungle',
            'Riven' => 'Top',
            'Rumble' => 'Top',
            'Ryze' => 'Middle',
            'Samira' => 'Bottom',
            'Sejuani' => 'Jungle',
            'Senna' => 'Support',
            'Seraphine' => 'Support',
            'Sett' => 'Top',
            'Shaco' => 'Jungle',
            'Shen' => 'Top',
            'Shyvana' => 'Jungle',
            'Singed' => 'Top',
            'Sion' => 'Top',
            'Sivir' => 'Bottom',
            'Skarner' => 'Jungle',
            'Sona' => 'Support',
            'Soraka' => 'Support',
            'Swain' => 'Support',
            'Sylas' => 'Middle',
            'Syndra' => 'Middle',
            'TahmKench' => 'Support',
            'Taliyah' => 'Jungle',
            'Talon' => 'Middle',
            'Taric' => 'Support',
            'Teemo' => 'Top',
            'Thresh' => 'Support',
            'Tristana' => 'Bottom',
            'Trundle' => 'Jungle',
            'Tryndamere' => 'Top',
            'TwistedFate' => 'Middle',
            'Twitch' => 'Bottom',
            'Udyr' => 'Jungle',
            'Urgot' => 'Top',
            'Varus' => 'Bottom',
            'Vayne' => 'Bottom',
            'Veigar' => 'Middle',
            'Velkoz' => 'Support',
            'Vex' => 'Middle',
            'Vi' => 'Jungle',
            'Viego' => 'Jungle',
            'Viktor' => 'Middle',
            'Vladimir' => 'Middle',
            'Volibear' => 'Top',
            'Warwick' => 'Jungle',
            'Wukong' => 'Jungle',
            'Xayah' => 'Bottom',
            'Xerath' => 'Support',
            'XinZhao' => 'Jungle',
            'Yasuo' => 'Middle',
            'Yone' => 'Middle',
            'Yorick' => 'Top',
            'Yuumi' => 'Support',
            'Zac' => 'Jungle',
            'Zed' => 'Middle',
            'Zeri' => 'Bottom',
            'Ziggs' => 'Bottom',
            'Zilean' => 'Support',
            'Zoe' => 'Middle',
            'Zyra' => 'Support'
        ];

        foreach ($championLanes as $championId => $lane) {
            $champion = Champion::find($championId);
            if ($champion) {
                
                $champion->lane = $lane;
                $champion->save();
            }
        }
    }
}